#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header


apt-get update
apt-get install -y nginx

echo "Holberton School" >/var/www/html/index.html
echo > "Ceci n'est pas une page" >/var/www/html/404.html
echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
           add_header X-Served-By $HOSTNAME;
          location / {
          root      /var/www/html;
          index     index.html;
          }
            location /redirect_me {                                                       
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;                                                 
        }
        
error_page 404 /notFound.html;
        location =/notFound.html {                                                       
           root      /var/www/html/;
            internal;                                        
        }
     }
" > /etc/nginx/sites-available/default

service nginx restart
