#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
#The name of the custom HTTP header must be X-Served-By
#The value of the custom HTTP header must be the hostname of the server Nginx is running on


echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
           add_header X-Served-By $HOSTNAME;
          location / {
          root      /var/www/html;
          index     index.html;
          }
            location /redirect_me {                                                       
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;                                                 
        }
        
error_page 404 /notFound.html;
        location =/not_found.html {                                                       
           root      /var/www/html/;
            internal;                                        
        }
     }
" > /etc/nginx/sites-available/default

service nginx restart
