#!/usr/bin/env bash
# install ngninx web server 
# create default nginx dirctory 
# configure nginx 
# we can display index.html using command curl localhost 
apt-get update
apt-get install -y nginx
mkdir /usr/share/nginx/html
touch /usr/share/nginx/html/index.html
echo "Holberton School for win !" > /usr/share/nginx/html/index.html
echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
          location / {
          root      /usr/share/nginx/html/;
          index     index.html;
          }
     }
" > /etc/nginx/sites-available/default

service nginx restart
