#!/usr/bin/env bash

apt-get update
apt-get install -y nginx
mkdir /usr/share/nginx/html
touch /usr/share/nginx/html/index.html
echo "Holberton School" > /usr/share/nginx/html/index.html
printf %s "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
          location / {
          root      /usr/share/nginx/html/;
          index     index.html;
          }
     }
" > /etc/nginx/sites-available/default

service nginx restart
