#!/usr/bin/env bash
# install ngninx web server we can display index.html using command curl localhost 


apt-get update
apt-get install -y nginx

touch /var/www/html/index.html
 echo "Holberton School" > /var/www/html/index.html

echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
          location / {
          root      /var/www/html;
          index     index.html;
          }
     }
" > /etc/nginx/sites-available/default

service nginx restart

