#!/usr/bin/env bash

#in this script i configure   ngninx to make redrection  to another page contains youtube video 


echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
          location / {
          root      /var/www/html;
          index     index.html;
          }
            location /redirect_me {                                                       
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;                                                 
        }
     }
" > /etc/nginx/sites-available/default

service nginx restart
