#!/usr/bin/env bash

#in this script i configure   ngninx to make redrection  to another page contains youtube video 

echo  "
    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        location / {
            root      /usr/share/nginx/html/;
            index     index.html;
        }
        location /redirect_me {                                                       
            rewrite ^ https://www.youtube.com/watch?v=8s22PZRXAIY permanent;                                                 
        }
    }
" > /etc/nginx/sites-available/default

service nginx restart
