#!/usr/bin/env bash

apt-get update
apt-get install -y nginx
mkdir /usr/share/nginx/html
touch /usr/share/nginx/html/index.html
touch /usr/share/nginx/html/404.html
echo "Holberton School" > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
printf %s "
    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        location / {
            root      /usr/share/nginx/html/;
            index     index.html;
        }
        location /redirect_me {                                                       
            return 301 https://www.youtube.com/watch?v=8s22PZRXAIY;                                                 
        }
        error_page 404 /404.html;
        location /404 {
            internal;
        } 
    }
" > /etc/nginx/sites-available/default

service nginx restart
