#!/usr/bin/env bash
#Configure Nginx to Use Custom Error Page 
touch /var/www/html/notFound.html
chmod o=wr /var/www/html/notFound.html
echo "Ceci n'est pas une page" > /var/www/html/notFound.html

echo "
     server {
          listen      80 default_server;
          listen      [::]:80 default_server;
          location / {
          root      /var/www/html;
          index     index.html;
          }
            location /redirect_me {                                                       
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;                                                 
        }
        
error_page 404 /notFound.html;
        location =/not_found.html {                                                       
           root      /var/www/html/;
            internal;                                        
        }

     }
" > /etc/nginx/sites-available/default

service nginx restart


