#!/usr/bin/env bash

#Configure Nginx to Use Custom Error Page 
echo "Ceci n'est pas une page" > /usr/share/nginx/html/notFound.html
echo >"
 
    server {
        listen      80 default_server;
        listen      [::]:80 default_server;
        location / {
            root      /usr/share/nginx/html/;
            index     index.html;
        }

error_page 404 /notFound.html;
        location =/not_found.html {                                                       
           root      /usr/share/nginx/html/;
            internal;                                        
        }


    }


" > /etc/nginx/sites-available/default

service nginx restart
